### ISSUE TITLE
Create a React component to view a CSV as a table

### ISSUE THREAD

**Issue by ruphy** [italia/daf-dataportal-public#3]
A table visualization is one of the most common for CSV files.

Write a React based component which can display a CSV as a table.

You can find many different datasets on http://www.dati.gov.it

**Comment by DavidePastore** [comment]
The url https://www.dati.gov.it is not accessible. Instead if you use http://www.dati.gov.it it works.

**Comment by WaYdotNET** [comment]
lol

**Comment by ruphy** [comment]
thanks, fixed

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed. Please refer to current repository: https://github.com/italia/daf-dataportal/issues/446.
