### ISSUE TITLE
Form di registrazione non salva tutti i dati sul profilo

### ISSUE THREAD

**Issue by sabas** [italia/daf-dataportal-public#32]
Ho inserito nome utente, nome e cognome, ma il nome non compare sul profilo, solo il cognome.

![image](https://user-images.githubusercontent.com/1304918/31316620-291c8dde-ac31-11e7-8706-fcd7211d4ce3.png)
![image](https://user-images.githubusercontent.com/1304918/31316623-364affae-ac31-11e7-9321-4b8cdf81479b.png)

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
