### ISSUE TITLE
Form di registrazione: riutilizzo icone

### ISSUE THREAD

**Issue by sabas** [italia/daf-dataportal-public#33]
Probabilmente bisognerebbe usare icone diverse per ogni campo

![image](https://user-images.githubusercontent.com/1304918/31316620-291c8dde-ac31-11e7-8706-fcd7211d4ce3.png)

**Comment by giux78** [comment]
Non credo ci siano icone per nome e cognome, al momento utilizziamo queste. Grazie comunque della segnalazione.
