### ISSUE TITLE
UI parole chiave nella scheda del dataset

### ISSUE THREAD

**Issue by sabas** [italia/daf-dataportal-public#34]
Invece che una lista di anchor, si potrebbe provare a mettere dei 'bottoni' sullo stile della pagina e togliendo la virgola come separatore
https://github.com/italia/daf-dataportal-public/blob/master/src/views/DatasetDetail.js#L96

Esempio copiando lo stile dal formato nella sezione Distribuzioni, togliendo l'underline e dando 2em di line-height sul paragrafo
![image](https://user-images.githubusercontent.com/1304918/31316752-188c62fc-ac34-11e7-8fe3-dbdf9cbf5396.png)

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
