### ISSUE TITLE
Estensione spaziotemporale del dato

### ISSUE THREAD

**Issue by sabas** [italia/daf-dataportal-public#38]
Ho visto diversi dataset pubblicati che sono relativi ad una limitata area geografica. Si dovrebbe esplicitare l'estensione sia spaziale sia temporale del dato.
Esempio:
* questo copre il solo anno 2017 https://dataportal.daf.teamdigitale.it/dataset/9e017722-b9b8-40d1-99fb-6c3efe4c8fa2
* questo copre il solo centro storico di Sedilo https://dataportal.daf.teamdigitale.it/dataset/fffa5fd0-f1aa-4aa5-b8ff-70dea139829f

Idealmente ogni dataset locale dovrebbe finire riconciliato ad un dataset nazionale, corretto?

**Comment by giux78** [comment]
Non tutti i dataset verrano riconciliati, e' un lavoro che andra' fatto in collaborazione con la PA, uno degli obbiettivi del DAF e' proprio quello di favorire meccanismi e processi di miglioramente della qualita' e quindi fruizione del dato.

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
