### ISSUE TITLE
Implement SPID Login

### ISSUE THREAD

**Issue by ruphy** [italia/daf-dataportal-public#4]
SPID is a required login method. Implement the login via SPID and save the resulting user data inside the FreeIPA instance.

Links:
- https://spid-regole-tecniche.readthedocs.io/

**Comment by alranel** [comment]
The most common component for authentication in Node applications is Passport. See https://github.com/italia/spid-passport/issues/1 for details about a Passport module for SPID.

However looks like this application uses Firebase for authentication. It's unclear to me how FreeIPA is involved. What's the best way to add SPID?

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed. Please refer to current repository: https://github.com/italia/daf-dataportal/issues/445.
