### ISSUE TITLE
some metadata are not visualized in the dataset landing page 

### ISSUE THREAD

**Issue by giorgialodi** [italia/daf-dataportal-public#51]
I noticed that for some datasets, the licenses, associated with their distributions, do not appear in the landing page. 

Example: let us take this dataset "Anticipazione provvisoria dell'indice dei prezzi al consumo - Anno 2017". 
Its distributions do not have any associated license; however, looking at the CKAN catalogue the license is specified by the data source https://ckan-open.daf.teamdigitale.it/dataset/anticipazione-provvisoria-dell-indice-dei-prezzi-al-consumo-anno-2017/resource/99241d28-4dcc-4588-b2ca-0e04d8d3a38c

The same comment can be applied to the "editore del dataset" (the organization that publishes the dataset): in the landing page of the dataset do not appear; however, in the serp page, for the same dataset, there is "pubblicato da: Comune di Bari".

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
