### ISSUE TITLE
Errore caricamento pagina log in

### ISSUE THREAD

**Issue by ndavanzo** [italia/daf-dataportal-public#54]
Riscontro un problema di caricamento della pagina di login da https://dataportal-private.daf.teamdigitale.it/
Probabilmente riguarda il caricamento di alcune librerie js. Di seguito il codice:

SCRIPT438: L'oggetto non supporta la proprietà o il metodo 'startsWith'
File: main.35f97cf5.js, riga: 1, colonna: 190648

L'errore si presenta con browser IE 11 (non con Chrome o Firefox).
Grazie
Nicola

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
