### ISSUE TITLE
Create a "map" React component

### ISSUE THREAD

**Issue by ruphy** [italia/daf-dataportal-public#6]
Some data has a lot of geographical meaning.
Create a "map" component, which can represent those data points and sets on a real map. For the map source, you can use [OpenStreetMap](https://openstreetmap.org)

Be inspired by Airbnb's design: when you click on a datapoint, you will go to the relevant point of the map.

You can find many different datasets on http://www.dati.gov.it

**Comment by WaYdotNET** [comment]
https://github.com/italia/daf-dataportal-public/issues/3#issuecomment-334916136

not work in https

**Comment by ruphy** [comment]
thank you, fixed!

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed. Please refer to current repository: https://github.com/italia/daf-dataportal/issues/444.
