### ISSUE TITLE
cannot create a private user story

### ISSUE THREAD

**Issue by esterpantaleo** [italia/daf-dataportal-public#83]
When I log in and try to create a data story, and I set "Privata" to "Si" I cannot select any "Organizzazione" and I cannot do anything (i.e., i cannot create a user story).
If the reason is that I do not belong to any organization, maybe there should be a dialog box explaining it, and explaining how to become part of an organization.
![screen shot 2018-02-26 at 14 56 03](https://user-images.githubusercontent.com/3217804/36674268-d7e6b63a-1b05-11e8-89a3-859ad2cf6aa7.png)

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
