### ISSUE TITLE
cannot include notebooks in data stories

### ISSUE THREAD

**Issue by esterpantaleo** [italia/daf-dataportal-public#85]
The only images that can be included in a data story are dashboards. It would be very useful to be able to add images through notebooks (markdown) or html links or other.

**Comment by esterpantaleo** [comment]
Plotly graphs can be embedded in webpages in at least three ways,

     <iframe src="https://plot.ly/...../file.embed"
        height="500" width="100%"
        scrolling="no" seamless="seamless"
        frameBorder="0">
     </iframe>

or 

    <img src="https://plot.ly/.../file.png">

see: https://plot.ly/r/embedding-plotly-graphs-in-HTML/ 
Alternatively plotly can produce HTML code, see https://help.plot.ly/embed-graphs-in-websites/

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
