### ISSUE TITLE
Automatic Logout After Timeout Period doesn't work

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-dataportal-public#87]
### Subject of the issue
The session doesn't expire, even after I come back after 8 or more hours

### Your environment
Safari, Chrome

### Steps to reproduce
Login to https://dataportal-private.daf.teamdigitale.it
Leave the browser open for several hours

### Expected behaviour
Automatic Logout After Timeout Period 

### Actual behaviour
the user session is still active even after several hours

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
