### ISSUE TITLE
[Nuova Dashboard]: Widget not found

### ISSUE THREAD

**Issue by mariaclaudia** [italia/daf-dataportal-public#96]
### Subject of the issue
It's not possible to add a widget created in superset because it's not listed 
### Your environment
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

### Steps to reproduce
Create a widget/slicer in Superset
Create a new Dashboard from "Toolkit">"Crea">"Nuova Dashboard"

<img width="1157" alt="screen shot 2018-05-04 at 17 50 13" src="https://user-images.githubusercontent.com/1733135/39638025-2a0797ec-4fc5-11e8-9edb-3363d8c27ae4.png">

Click on "Aggiungi Widget" 
Select "Superset", type "Elezioni" or "Interno" or some token related to the widget title

### Expected behaviour
The widgets with "Elezioni" in the title should be listed

### Actual behaviour
No widget listes
<img width="1262" alt="screen shot 2018-05-04 at 17 47 07" src="https://user-images.githubusercontent.com/1733135/39637953-e34f4ae8-4fc4-11e8-8ae6-75849df13f05.png">

It's should be possible to choose between different widgets created in Superset with "Elezioni" in the title

<img width="949" alt="screen shot 2018-05-04 at 17 58 10" src="https://user-images.githubusercontent.com/1733135/39637930-c71f870c-4fc4-11e8-865d-d2b6ff982ee0.png">

**Comment by giux78** [comment]
@mariaclaudia it is the wrong repo it should be in daf-dataportal. A part of that the problem is due to the fact that private slice can be only in private stories and viceversa. Try to make a private story and you will be able to see the slice.  Move the issue to the right repo

**Comment by mariaclaudia** [comment]
Thanks @giux78, I moved the [issue](https://github.com/italia/daf-dataportal/issues/229), anyway I think that both slicers should have the same properties, they are based on the same open dataset.
